# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - ly-python-func-v1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.10' # set this to the python version to use (supports 3.6, 3.7, 3.8)
  RESOURCE_GROUP: 'ResourceGroup' # set this to the resource group which contains your function app
  FUNCTION_APP_NAME: 'ly-python-func-v1' # set this to the name of the function app



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:  
    #   - name: 'Checkout GitHub Action'
    #     uses: actions/checkout@v3

    #   - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: ${{ env.PYTHON_VERSION }}

    #   - name: 'Resolve Project Dependencies Using Pip'
    #     shell: bash
    #     run: |
    #       pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt --target=".python_packages/lib/site-packages"
    #       popd

      # - name: Login to Azure
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0F166C8539FB44A2893A3A939D0BF6EA }}
      #     tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4EEE4A7D8114B70B990F44048BBF0B3 }}
      #     subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC6F86BE210A490C9A0E19B23CFE6057 }}

    #   - name: Add Run from Package Settings 
    #     uses: azure/appservice-settings@v1
    #     id: settings
    #     with:
    #       app-name: 'ly-python-func-v1'
    #       slot-name: 'Production'
    #       mask-inputs: false
    #       app-settings-json: '[{ "name": "WEBSITE_RUN_FROM_PACKAGE", "value": "1", "slotSetting": false }]'
            
    #   - name: 'Deploy to Azure Functions'
    #     uses: Azure/functions-action@v1
    #     id: deploy-to-function
    #     with:
    #       app-name: 'ly-python-func-v1'
    #       slot-name: 'Production'
    #       package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    #       scm-do-build-during-deployment: false
    #       enable-oryx-build: false
      
      - name: Get Runner Public IP Address 
        id: ip
        uses: candidob/get-runner-ip@v1.0.0

      - name: See IP Addresses
        run: |
            echo ${{ steps.ip.outputs.ipv4 }}
            echo ${{ steps.ip.outputs.ipv6 }}
            echo ${{ steps.ip.outputs.ipv4 }}/27

      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
                az account show
                az storage -h
                az webapp config access-restriction add -g ${{ env.RESOURCE_GROUP }} -n ${{ env.FUNCTION_APP_NAME}} --rule-name github deploy --action Allow --ip-address ${{ steps.ip.outputs.ipv4 }}/27 --priority 200
        